name: smart_dhaka_app
description: A Flutter application for Smart Dhaka

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  provider: ^6.0.5
  fl_chart: ^0.69.2
  geolocator: ^12.0.0
  http: ^0.13.6
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/config/frontend.env

